#!/bin/bash
# the createLoopBack function

#set -ex

createLoopBack() {
  for i in {2..4}; 
    do 
      # check if loopback interface does not exist
      if ! ifconfig lo0 | grep -q "127.0.0.$i"; then
        sudo ifconfig lo0 alias  127.0.0.$i up; 
        echo "Created loopback interface 127.0.0.$i"
      fi
    done
}

# Prepare command list if --additional-args is passed

if [[ ! -z $ADDITIONAL_ARGS ]]; then
  echo "Additional args: $ADDITIONAL_ARGS"
fi
if [[ ! -z $YB_TSERVER_FLAGS ]]; then
  echo "yb-tservers flags: $YB_TSERVER_FLAGS"
fi
if [[ ! -z $YB_MASTER_FLAGS ]]; then
  echo "yb-master flags: $YB_MASTER_FLAGS"
fi

# the create function
create() {
  createLoopBack
  echo "Creating YugabyteDB cluster"
  mkdir -p $HOME/yugadata/node-2 $HOME/yugadata/node-3 $HOME/yugadata/node-4

  # Start first instance
  echo "Starting instance 1:- host: 127.0.0.2 base_dir: $HOME/yugadata/node-2"
  yugabyted start \
    --base_dir=$HOME/yugadata/node-2 \
    --advertise_address=127.0.0.2 --tserver_flags="$YB_TSERVER_FLAGS" --master_flags="$YB_MASTER_FLAGS" > /dev/null

  # Join other instances
  for i in {3..4}; do
    echo "Starting and joining instance $i:- host: 127.0.0.$i base_dir: $HOME/yugadata/node-$i"
    yugabyted start \
      --base_dir=$HOME/yugadata/node-$i \
      --join=127.0.0.2 \
      --advertise_address=127.0.0.$i --tserver_flags="$YB_TSERVER_FLAGS" --master_flags="$YB_MASTER_FLAGS" --ui false > /dev/null
  done

  # Get the status
  yugabyted status --base_dir=$HOME/yugadata/node-2
}
# the start function
start() {
  createLoopBack
  echo "Starting YugabyteDB"
  for i in {2..4}; do
    echo "Starting instance $i:- host: 127.0.0.$i base_dir: $HOME/yugadata/node-$i"
    yugabyted start \
      --base_dir $HOME/yugadata/node-$i \
      --background=true --tserver_flags="$YB_TSERVER_FLAGS" --master_flags="$YB_MASTER_FLAGS" > /dev/null
  done
  # Get the status
  yugabyted status --base_dir=$HOME/yugadata/node-2
}

# the Stop function
stop() {
  echo "Stopping YugabyteDB"
  for i in {2..4}; do
    yugabyted stop \
    --base_dir $HOME/yugadata/node-$i
  done
}

# the destroy function
destroy() {
  echo "Destroying YugabyteDB"
  for i in {2..4}; do
    yugabyted destroy --base_dir $HOME/yugadata/node-$i
  done
  rm -rf $HOME/yugadata
}


restart() {
  stop
  start
}

# the status function
status() {
  if ! ifconfig lo0 | grep -q "127.0.0.2"; then
    echo "YugabyteDB is not running"
    exit 1
  fi
  yugabyted status --base_dir=$HOME/yugadata/node-2
}

case "$1" in
  create)
    create
    ;;
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  status)
    status
    ;;
  destroy)
    destroy
    ;;
  recreate)
    destroy
    create
    ;;
  *)
    echo "Usage: $0 create|start|stop|restart|status|destroy"
    exit 1
    ;;
esac
